# Generated by Django 2.0.7 on 2018-10-27 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='api',
            name='region',
            field=models.CharField(default='N/A', max_length=100),
        ),
    ]
